# Generated by Django 4.2 on 2026-03-16 15:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['-submission_date']},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-registration_date']},
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='reg_date',
            new_name='registration_date',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='file',
        ),
        migrations.AddField(
            model_name='conference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='organiser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organised_conferences', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='conference',
            name='submission_deadline',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='theme',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='abstract',
            field=models.TextField(default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='file_url',
            field=models.URLField(default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='conference',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paper',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='api.conference'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='registration',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.conference'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('organiser', 'Conference Organiser'), ('author', 'Paper Author'), ('attendee', 'Conference Attendee')], default='attendee', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('user', 'conference')},
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('session_type', models.CharField(choices=[('keynote', 'Keynote'), ('workshop', 'Workshop'), ('panel', 'Panel Discussion'), ('talk', 'Talk')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.conference')),
                ('panel_members', models.ManyToManyField(blank=True, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'time_slot'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('cash', 'Cash')], max_length=20)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.registration')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
